### ISSUE TITLE
Feature: uninstall

### ISSUE THREAD

**Issue by distantnative** [getkirby/cli#1]
Just for convenience at some point: have a `kirby uninstall` command

**Comment by luxlogica** [comment]
Super useful. Suggestion for syntax:

```
kirby uninstall:field
```

...would provide a list of all installed fields. Same would be for tags, plugins, etc.

```
kirby uninstall:field myfield
```

...woud actually delete the field files and directories.

**Comment by luxlogica** [comment]
Ok, looking at the docs, I think I got this wrong. The 'install' command is only for installing the kits, and the different components of Kirby itself, like 'core' and 'panel'. Plugins have their own command, with sub-commands, and tags, fields, blueprints, etc., have a 'make' command. In that case, there may need to be several different commands...

```
kirby uninstall
```
...would be for Kirby core/panel and its components. It could have sub-commands, such as:

```
kirby uninstall:core
kirby uninstall:panel
kirby uninstall:index
kirby uninstall:htaccess
```

In order to remain consistent with the existing syntax, plugins would probably need an extra sub-command:

```
kirby plugin:uninstall $plugin
```

And finally, for blueprints, controllers, snippets, templates, users, and tags - all of which use a 'make' command - it may be useful to have...:

```
kirby delete:tag $tagname
```

**Comment by bastianallgeier** [comment]
I implemented all of them on the develop branch except: 

```
kirby uninstall:core
kirby uninstall:index
kirby uninstall:htaccess
```

I feel like those shouldn't exist. But the rest is awesome :)
